language: node_js
sudo: false
node_js: 
  - "node"
cache:
  directories:
    - ~/.npm
    - ~/.cache
stages:
  - name: functional-test
  - name: deploy
    if: branch =~ /(master|(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)|^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$)/
  - name: smoke-test
    if: branch = master
jobs:
  include:
    - stage: functional-test
      script: bash ./ci/functional-test
    - stage: deploy
      script: bash ./ci/deploy
      before_deploy: bash ./scripts/removeDevDep
      deploy:
        provider: heroku
        skip_cleanup: true
        api_key:
          secure: "$HEROKU_KEY"
        app: $HEROKU_APP_NAME
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ (^master|^release-v\d.\d.\d|^\d.\d.\d)
    - stage: smoke-test
      script: bash ./ci/smoke-test
