language: node_js
sudo: false
node_js: 
  - "node"
cache:
  directories:
    - ~/.npm
    - ~/.cache
stages:
  - name: functional-test
  - name: deploy
    if: branch = master
  - name: smoke-test
    if: branch = master
jobs:
  include:
    - stage: functional-test
      script: bash ./ci/functional-test
    - stage: deploy
      script: bash ./ci/deploy
      before_deploy: bash ./scripts/removeDevDep
      deploy:
        provider: heroku
        skip_cleanup: true
        api_key:
          secure: "$HEROKU_KEY"
        on:
          all_branches: true
          condition: "branch =~ /(^master|^release-v\d.\d.\d|^\d.\d.\d)/"
        app: 
          master: $HEROKU_APP_NAME
    - stage: smoke-test
      script: bash ./ci/smoke-test
