language: node_js
sudo: false
node_js: 
  - "node"
cache:
  directories:
    - ~/.npm
    - ~/.cache
install:
  - npm ci
stages:
  - name: functional-test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: functional-test
      script: ./ci/functional-test
    - stage: deploy 
      script: ./ci/deploy
      env:
        - NPM_CONFIG_PRODUCTION=true
      deploy: &heroku
        provider: heroku
        skip_cleanup: true
        app: $HEROKU_APP_NAME
        api_key:
          secure: "$HEROKU_KEY"
        on:
          branches:
            - master
   